name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -race ./...

      - name: Build application
        run: go build -v ./...

      - name: Install swag and generate docs
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init

      - name: Check if PR is for minor/patch updates
        id: check-update-type
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const isMinorOrPatch = title.includes('minor') || title.includes('patch') ||
                                  !title.includes('major');
            return isMinorOrPatch;

      - name: Enable auto-merge for minor/patch updates
        if: steps.check-update-type.outputs.result == 'true'
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR
        if: steps.check-update-type.outputs.result == 'true'
        run: |
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
